language: node_js
node_js:
  - "8"
dist: trusty
services: 
  - mongodb
  - redis-server
env: 
  - NODE_ENV=ci
cache: 
  directories: 
    - node_modules
    - client/node_modules
install: 
  - yarn
  - yarn run build
script:
  - nohup yarn run start
  - sleep 3
  - yarn run test